### ISSUE TITLE
RubyGem release 0.1.4

### ISSUE THREAD

**Issue by wconrad** [bnix/double-bag-ftps#16]
@bnix Gem version 0.1.4 is ready for release.

**Comment by wconrad** [comment]
By the way: I read that a gem may have multiple owners.  If you're OK with me doing releases, you could add me (kf7qga@gmail.com) as a gem owner.

**Comment by bnix** [comment]
@wconrad I've added you as a gem owner 👍

**Comment by wconrad** [comment]
I've finally released 0.1.4.
